### PR TITLE
auto adjust height for Images

### PR DESCRIPTION
**Pull request by roipeker**
Made a little code reformatting.
Included `_ImageRow` and modified `_EnlargableImage` to expand in the available height..

### CODE REVIEW

**Comment by escamoteur** [comment]
Hi Roi,

many thanks. When I make the Windows very narrow I get this Exception here where I have no idea what it triggered.

image

Is it the Stack that does the trick that the Text defines the height but the Image fills then the full height?

Cheers
Thomas

**Comment by roipeker** [comment]
Hi @escamoteur, to be honest i just focus on the concept of image resize. I remember there was some media query detection for screens resolutions that changes the layout of that view. And the exception happens when it build the widgets for smaller sizes... didn't wanna mess much with code to avoid more inconveniences. But if you want i can take a look. There were way too many flags in the code for some "admin" mode i think, which i couldn't run, so 🤷‍♂️ if I will break things further.

**Comment by escamoteur** [comment]
Hi Roi,
thanks. would be awesome if you could have another look at it. if you launch the app using the staging launch configuration in VS code you can login by double clicking on the DevsHelpDevsLogo.
this exception didn't happen before your change. I really wonder what it is.
I will add the aspect ratio and a max Image size on this branch and push it again.

**Comment by escamoteur** [comment]
I changed the layout again. It didn't look good with all images in different sizes.
Bzw the Excection came from the Stack you added :-) I think now it's fine

**Pull request merged**
