### PR TITLE
add vertical scrolling for smaller devices

### PR DESCRIPTION
**Pull request by 0xdanny**
I simply added a couple of `SingleChildScrollView` widgets to enable vertical scrolling on smaller screens such as mobile devices

### CODE REVIEW

**Comment by jaumard** [comment]
Thanks :) we notice that yesterday, it was indeed needed.

**Review by jaumard — APPROVED** [review]

**Comment by 0xdanny** [comment]
Hello, thanks for approving @jaumard. I also figured out that horizontal nav on the `DataTable` might be needed on mobile devices. What do you think of an `InteractiveViewer` on the `DataTable` widget? I hear a lot about performance issues with it which I've also seen in testing.

**Comment by jaumard** [comment]
Hello

On mobile I would rather hide some not that useful column instead of InteractiveViewer, because we already have some perf issues reported by some so let's not add more with this lol :D

**Comment by 0xdanny** [comment]
> Hello
> 
> On mobile I would rather hide some not that useful column instead of InteractiveViewer, because we already have some perf issues reported by some so let's not add more with this lol :D

Okay that's fine. The other way we could do it is via more and more `SingleChildScrollView` :/ , but we'll lose the Expanded and then it'll look smaller on desktop.

I guess we could just hide columns as you said esp the image column.

**Pull request merged**
